// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Import the generated Database type (create this file with the Supabase CLI):
// npx supabase gen types typescript --project-id <your-project-id> --schema public > src/integrations/supabase/types.ts
import type { Database } from './types';

// Supabase project configuration
const SUPABASE_URL = 'https://pbdwkbcpbrrxnvyzjrfa.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'sb_publishable_yNTyuAkgVBipucKRQ4WErQ_B28NNFPS';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL || '', SUPABASE_PUBLISHABLE_KEY || '', {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});